export const CONVERSATION_TEXT_KEYS = [
  'text',
  'rawText',
  'content',
  'message',
  'prompt',
  'response',
  'summary',
  'thinking',
  'reasoning',
  'result',
  'output',
  'arguments',
  'input',
  'parts',
  'segments',
  'state',
  'context',
  'codeBlocks',
  'suggestedCodeBlocks',
  'toolResults',
  'diffHistories',
  'selections',
  'suggestedDiffs',
  'code_context',
  'suggested_diffs',
] as const
