import { CODEX_SKILL_TRIM_MARKERS } from '../constants/CODEX_SKILL_TRIM_MARKERS'

/**
 * Renders the `[[skills.config]]` block that keeps Codex under its skills
 * context budget.
 *
 * Codex discovers every `SKILL.md` beneath the canonical skills directory, and
 * the aggregate bundles carry nested children. Past that budget it drops every
 * description and omits skills outright, which leaves it unable to route to any
 * of them. Disabling the aggregate parents does not help: the children are
 * discovered on their own.
 */
export const renderCodexSkillTrim = (disabledSkillPaths: readonly string[]) => {
  const entries = disabledSkillPaths
    .toSorted((left, right) => left.localeCompare(right))
    .map((path) => `[[skills.config]]\npath = "${path}"\nenabled = false`)
    .join('\n\n')

  return [
    CODEX_SKILL_TRIM_MARKERS.start,
    '# Generated by `pnpm run skills:link`. Edits between these markers are lost',
    '# on the next run; everything outside them is preserved.',
    entries,
    CODEX_SKILL_TRIM_MARKERS.end,
  ]
    .filter((section) => section !== '')
    .join('\n')
}
