export const ATOMIC_FILE_RULE_SLIM = [
  '# Atomic File Rule (Non-Negotiable)',
  '',
  'ONE file = ONE exported unit = ONE responsibility. No helpers, no private',
  'functions, no inline utilities. If in doubt, split.',
  '',
  '## Hard constraints',
  '',
  '- A file contains **exactly one** top-level unit: `function`, `type` / `interface`, `class`, `constant`, or `hook`.',
  '- No internal/private helpers, inline utilities, or grouped `utils.ts` / `helpers.ts`.',
  '- No `// cleaner this way` justifications.',
  '- Every dependency is an explicit `import` from another file.',
  '',
  '## Decision rule',
  '',
  'If a line is not the **primary responsibility** of the file, extract it and import it explicitly.',
  '',
  '## Functions',
  '',
  '- A function does exactly one thing.',
  '- `X + Y + Z` = three functions, three files, three imports.',
  '- If the function reads like a sentence with a conjunction ("and", "then", "also"), split it.',
  '',
  'Full detail (banned-patterns table, ts-morph extraction example, self-check checklist) is listed in the rules index below.',
].join('\n')
