export const GLOBAL_INSTRUCTIONS = [
  '## Identity / Emails',
  '',
  '- Identities are instance data, not engine data: the addresses live in the',
  '  instance guidance this repository renders alongside, never in this file.',
  '- Keep work and personal/side-project addresses apart, and use each only for',
  '  its own kind of work: personal projects, test recipients and account lookups',
  '  go to the personal address.',
  '- When the project context is unclear, ask before using either identity.',
  '',
  '## Git Commits (hard rule, no exceptions)',
  '',
  '- Never add assistant, model, vendor, or tool attribution footers (e.g. `Co-Authored-By`, `Generated with`).',
  '- Never reference an assistant, model, or AI tool in commit messages, PR titles, or PR descriptions.',
  '- Write commit messages as if the human author wrote them. Use the existing `user.name` and `user.email` from git config.',
  '- This rule applies even if the user does not mention it. Do not ask, do not opt-in, do not negotiate.',
  '',
  '## Written Artifacts',
  '',
  '- All code, comments, identifiers, docs, commit messages, PR titles/descriptions, and generated artifacts must be written in English.',
  '- The only exception is when the user explicitly requests another language for a specific artifact.',
  "- Chat replies may use the user's language.",
  '',
  '## Memory',
  '',
  '- Before asking about previously established project conventions, deployment details, credentials locations, CI behavior, or past decisions, check memory first.',
  '- Prefer `atrium search "<topic>" --project .` for targeted recall in this project, without `--project` when the answer may lie in other work.',
  '- Save only high-signal memory: decisions, gotchas, feedback, bugs, and runbooks.',
  '- The project is derived from the enclosing repository root, and its worktrees count as one project.',
  '- The canonical archive is `rocket-agents` and the index is derived and disposable: sync the archive, never the index.',
  '',
  '## Current Documentation',
  '',
  '- When working with libraries, frameworks, SDKs, CLIs, cloud services, or APIs, fetch current docs before relying on memory.',
  '- Prefer the Context7 MCP server for package, framework, and API documentation.',
  "- Resolve the library first, then query the selected library docs with the user's concrete task.",
  '',
]
